name = "hadestv"
compatibility_date = "2026-01-01"
pages_build_output_dir = "./dist"

[build]
command = "bun run build"

[vars]
DUKTEK_BASE = "https://cdn.jsdelivr.net/gh/movietrailersxxi-pixel/web@main/assets"
