import { rm, cp, readFile, writeFile } from "node:fs/promises";

// Clean previous build
await rm("./dist", { recursive: true, force: true });

// Bundle the client-side code (hydration glue — server already rendered SSR).
const buildResult = await Bun.build({
  entrypoints: ["./src/client.tsx"],
  outdir: "./dist",
  minify: true,
  target: "browser",
  naming: "client.[ext]",
});

if (!buildResult.success) {
  // oxlint-disable-next-line no-console
  for (const log of buildResult.logs) console.error(log);
  process.exit(1);
}

// Copy static assets
await cp("./src/style.css", "./dist/style.css");

// Embed client.js and style.css into a TS module so the Pages Function can
// serve them directly. Pages Functions' catch-all [[path]].ts claims every
// URL (including /style.css and /client.js) before static-asset serving
// kicks in, so the function has to answer for them itself.
const styleCssText = await readFile("./dist/style.css", "utf8");
const clientJsText = await readFile("./dist/client.js", "utf8");
const staticBundle =
  `// AUTO-GENERATED by src/index.ts — do not edit by hand.\n` +
  `export const STYLE_CSS = ${JSON.stringify(styleCssText)};\n` +
  `export const CLIENT_JS = ${JSON.stringify(clientJsText)};\n` +
  `export const STYLE_CSS_HASH = ${JSON.stringify(styleCssText.length)};\n` +
  `export const CLIENT_JS_HASH = ${JSON.stringify(clientJsText.length)};\n`;
await writeFile("./src/static-bundle.ts", staticBundle);

// oxlint-disable-next-line no-console
console.log("Build complete → ./dist/ + src/static-bundle.ts");
